version: "3.3"
volumes:
  data:
services:
  myphp:
    build: ./
    ports:
      - "80:80"
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: hallo_db
      MARIADB_USER: manuel
      MARIADB_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"